os: linux
sudo: required
language: python
services: docker

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git
  - 'sudo apt-get update --qqq && 
     sudo apt-get install -y squashfs-tools ibarchive-dev'
  - 'git clone https://github.com/singularityware/singularity.git singularity_src &&
    cd singularity_src && git fetch --all && git checkout 2.6.0 &&
    ./autogen.sh && ./configure --prefix=/usr/local && 
    make && sudo make install && cd .. && rm -rf singularity_src'

script:
  - './ci-util/build-docker.sh : x11vnc/desktop &&
     ./ubuntu_desktop.py -t $TRAVIS_BRANCH -d -n -V && docker stop $(docker ps -q) &&
     singularity pull docker://x11vnc/desktop:$TRAVIS_BRANCH'

after_success:
  - ./ci-util/trigger-via-api.sh
