os: linux
dist: trusty
sudo: required
language: python
services: docker

env:
  - XVFB=1
  - XVFB=0

before_install:
  # Start up xvfb
  - '[[ "$XVFB" != "1" ]] || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
     --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'

before_script:
  - '[[ "$XVFB" != "1" ]] || export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start'

script:
  - docker --version
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_USERPASS"
  # Build only if the commit range of a push contains Dockerfile or .travis.yml
  - '[[ "$TRAVIS_EVENT_TYPE" == "push" && -n "$TRAVIS_COMMIT_RANGE" &&
        -z "$(git diff --name-only $TRAVIS_COMMIT_RANGE |
            grep -e Dockerfile -e .travis.yml)" ]] || [[ "$XVFB" != "1" ]] ||
     (docker build --tag x11vnc/desktop:16.04 --tag x11vnc/desktop:latest . &&
      docker push x11vnc/desktop &&
      touch success)'
  # Test scripts
  - ./docker_desktop.py -d -n -t latest && docker stop $(docker ps -q)
  - docker images
